// ═══════════════════════════════════════════════
// DSL GENERATION
// ═══════════════════════════════════════════════
function buildDSL() {
  const pipeline = {
    $pipeline: "viewforge/1.0",
    sources: {},
    steps: [],
    output: null
  };

  state.nodes.forEach(node => {
    if (node.type === 'source') {
      pipeline.sources[node.data.sourceName] = {
        $ref: node.data.sourceName,
        select: node.data.fields ? node.data.fields.map(f => f.name) : "*"
      };
    }
  });

  // topological-ish order via edges
  state.nodes.forEach(node => {
    if (node.type === 'source') return;
    const inputs = state.edges.filter(e => e.to === node.id).map(e => {
      const src = state.nodes.find(n => n.id === e.from);
      return src ? (src.data.sourceName || src.data.label || src.id) : e.from;
    });

    let step = { $op: node.type, id: node.id };
    if (inputs.length) step.$from = inputs.length === 1 ? inputs[0] : inputs;

    if (node.type === 'join') {
      step.type = node.data.joinType || 'inner';
      step.on = node.data.joinKey || '';
    } else if (node.type === 'filter') {
      step.where = node.data.condition || '';
    } else if (node.type === 'map') {
      step.fields = (node.data.fields || []).map(f => f.name);
      if (node.data.mapping) step.compute = node.data.mapping;
    } else if (node.type === 'aggregate') {
      step.fn = node.data.aggFn || 'sum';
      step.field = node.data.aggField || '';
    } else if (node.type === 'groupby') {
      step.by = (node.data.groupFields || '').split(',').map(s=>s.trim()).filter(Boolean);
    } else if (node.type === 'sort') {
      step.by = node.data.sortField || '';
      step.order = node.data.sortOrder || 'asc';
    } else if (node.type === 'output') {
      step.name = node.data.outputName || 'my_view';
      if (node.data.outputSchema) step.shape = node.data.outputSchema;
      pipeline.output = step.name;
    }
    pipeline.steps.push(step);
  });

  // when in builder view, inject builder schema into output step
  if (activeCanvasView === 'builder' && builderTree.length) {
    const name = document.getElementById('builder-output-name')?.value || 'my_view';
    pipeline.output = name;
    const outStep = pipeline.steps.find(s => s.$op === 'output');
    if (outStep) {
      outStep.name = name;
      outStep.shape = builderToSchema(builderTree);
    } else {
      pipeline.steps.push({ $op: 'output', name, shape: builderToSchema(builderTree) });
    }
  }

  return pipeline;
}

function refreshDSL() {
  const dsl = buildDSL();
  const pretty = syntaxHighlight(JSON.stringify(dsl, null, 2));
  document.getElementById('dsl-output').innerHTML = pretty;
  generateCode(state.currentLang);
}

function syntaxHighlight(json) {
  return json
    .replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, match => {
      let cls = 'num';
      if (/^"/.test(match)) {
        if (/:$/.test(match)) cls = 'key';
        else cls = 'str';
      } else if (/true|false/.test(match)) cls = 'kw';
      else if (/null/.test(match)) cls = 'kw';
      return `<span class="${cls}">${match}</span>`;
    });
}

function copyDSL() {
  const dsl = JSON.stringify(buildDSL(), null, 2);
  navigator.clipboard.writeText(dsl).catch(()=>{});
  document.getElementById('status-msg').textContent = 'DSL copied!';
  setTimeout(()=> document.getElementById('status-msg').textContent = '', 2000);
}

function showDSL() {
  const dsl = JSON.stringify(buildDSL(), null, 2);
  document.getElementById('modal-dsl-content').innerHTML = syntaxHighlight(dsl);
  openModal('modal-dsl');
}

// ═══════════════════════════════════════════════
// CODE GENERATION
// ═══════════════════════════════════════════════
function switchLang(lang, btn) {
  document.querySelectorAll('.lang-tab').forEach(t => t.classList.remove('active'));
  btn.classList.add('active');
  state.currentLang = lang;
  generateCode(lang);
  switchRTab('codegen', document.querySelector('.rtab:nth-child(3)'));
}

function generateCode(lang) {
  const dsl = buildDSL();
  let code = '';
  if (lang === 'js') code = genJS(dsl);
  else if (lang === 'kotlin') code = genKotlin(dsl);
  else if (lang === 'python') code = genPython(dsl);
  else if (lang === 'sql') code = genSQL(dsl);
  document.getElementById('codegen-output').textContent = code;
}

function genJS(dsl) {
  const sourceNames = Object.keys(dsl.sources);
  let lines = [
    `// Generated by ViewForge`,
    `// Pipeline: ${dsl.$pipeline}`,
    ``,
    `const { ${sourceNames.join(', ')} } = dataSources;`,
    ``
  ];

  dsl.steps.forEach(step => {
    const from = Array.isArray(step.$from) ? step.$from[0] : (step.$from || 'data');
    const varName = step.id || 'result';
    if (step.$op === 'join') {
      const right = Array.isArray(step.$from) ? step.$from[1] : 'rightData';
      lines.push(`const ${varName} = ${from}.flatMap(l =>`);
      lines.push(`  ${right}.filter(r => r.${step.on} === l.${step.on})`);
      lines.push(`    .map(r => ({ ...l, ...r }))`);
      lines.push(`);`);
    } else if (step.$op === 'filter') {
      lines.push(`const ${varName} = ${from}.filter(row => ${step.where || 'true'});`);
    } else if (step.$op === 'map') {
      const fields = (step.fields || []).map(f => `${f}: row.${f}`).join(', ');
      lines.push(`const ${varName} = ${from}.map(row => ({ ${fields} }));`);
    } else if (step.$op === 'aggregate') {
      if (step.fn === 'sum') lines.push(`const ${varName} = ${from}.reduce((acc, row) => acc + (row.${step.field} || 0), 0);`);
      else if (step.fn === 'count') lines.push(`const ${varName} = ${from}.length;`);
      else if (step.fn === 'avg') lines.push(`const ${varName} = ${from}.reduce((a, r) => a + r.${step.field}, 0) / ${from}.length;`);
      else if (step.fn === 'min') lines.push(`const ${varName} = Math.min(...${from}.map(r => r.${step.field}));`);
      else if (step.fn === 'max') lines.push(`const ${varName} = Math.max(...${from}.map(r => r.${step.field}));`);
    } else if (step.$op === 'groupby') {
      const byFields = step.by || [];
      lines.push(`const ${varName} = Object.values(${from}.reduce((acc, row) => {`);
      lines.push(`  const key = ${byFields.map(f => `row.${f}`).join(' + "_" + ') || 'row'};`);
      lines.push(`  if (!acc[key]) acc[key] = { ${byFields.map(f => `${f}: row.${f}`).join(', ')}, items: [] };`);
      lines.push(`  acc[key].items.push(row);`);
      lines.push(`  return acc;`);
      lines.push(`}, {}));`);
    } else if (step.$op === 'sort') {
      const dir = step.order === 'desc' ? -1 : 1;
      lines.push(`const ${varName} = [...${from}].sort((a, b) =>`);
      lines.push(`  a.${step.by} < b.${step.by} ? ${-dir} : a.${step.by} > b.${step.by} ? ${dir} : 0`);
      lines.push(`);`);
    } else if (step.$op === 'output') {
      lines.push(`const ${step.name} = ${from};`);
      lines.push(`return ${step.name};`);
    }
    lines.push('');
  });
  return lines.join('\n');
}

function genKotlin(dsl) {
  const sourceNames = Object.keys(dsl.sources);
  let lines = [
    `// Generated by ViewForge`,
    `// Pipeline: ${dsl.$pipeline}`,
    ``,
    `fun buildView(dataSources: Map<String, List<Map<String, Any?>>>): List<Map<String, Any?>> {`,
    `  val ${sourceNames.map(n=>`${n} = dataSources["${n}"] ?: emptyList()`).join('\n  val ')}`,
    ``
  ];
  dsl.steps.forEach(step => {
    const from = Array.isArray(step.$from) ? step.$from[0] : (step.$from || 'data');
    const varName = step.id || 'result';
    if (step.$op === 'filter') {
      lines.push(`  val ${varName} = ${from}.filter { it["${(step.where||'').split(' ')[0]}"] != null }`);
    } else if (step.$op === 'map') {
      const fields = (step.fields || []).map(f => `"${f}" to it["${f}"]`).join(', ');
      lines.push(`  val ${varName} = ${from}.map { mapOf(${fields}) }`);
    } else if (step.$op === 'sort') {
      lines.push(`  val ${varName} = ${from}.sortedBy { it["${step.by}"] as? Comparable<Any> }`);
    } else if (step.$op === 'aggregate') {
      if (step.fn === 'count') lines.push(`  val ${varName} = ${from}.size`);
      else lines.push(`  val ${varName} = ${from}.sumOf { (it["${step.field}"] as? Double) ?: 0.0 }`);
    } else if (step.$op === 'output') {
      lines.push(`  return ${from} // ${step.name}`);
    }
    lines.push('');
  });
  lines.push('}');
  return lines.join('\n');
}

function genPython(dsl) {
  const sourceNames = Object.keys(dsl.sources);
  let lines = [
    `# Generated by ViewForge`,
    `# Pipeline: ${dsl.$pipeline}`,
    ``,
    `def build_view(data_sources):`,
    `    ${sourceNames.map(n => `${n} = data_sources.get("${n}", [])`).join('\n    ')}`,
    ``
  ];
  dsl.steps.forEach(step => {
    const from = Array.isArray(step.$from) ? step.$from[0] : (step.$from || 'data');
    const varName = (step.id || 'result').replace(/[^a-z0-9_]/gi, '_');
    if (step.$op === 'filter') {
      lines.push(`    ${varName} = [row for row in ${from} if ${step.where || 'True'}]`);
    } else if (step.$op === 'map') {
      const fields = (step.fields || []).map(f => `"${f}": row["${f}"]`).join(', ');
      lines.push(`    ${varName} = [{${fields}} for row in ${from}]`);
    } else if (step.$op === 'sort') {
      const rev = step.order === 'desc' ? 'True' : 'False';
      lines.push(`    ${varName} = sorted(${from}, key=lambda r: r.get("${step.by}"), reverse=${rev})`);
    } else if (step.$op === 'aggregate') {
      if (step.fn === 'sum') lines.push(`    ${varName} = sum(row.get("${step.field}", 0) for row in ${from})`);
      else if (step.fn === 'count') lines.push(`    ${varName} = len(${from})`);
      else if (step.fn === 'avg') lines.push(`    ${varName} = sum(row.get("${step.field}", 0) for row in ${from}) / max(len(${from}), 1)`);
    } else if (step.$op === 'join') {
      const right = Array.isArray(step.$from) ? step.$from[1] : 'right_data';
      lines.push(`    _right_idx = {r["${step.on}"]: r for r in ${right}}`);
      lines.push(`    ${varName} = [{**l, **_right_idx[l["${step.on}"]]} for l in ${from} if l.get("${step.on}") in _right_idx]`);
    } else if (step.$op === 'output') {
      lines.push(`    return ${from}  # ${step.name}`);
    }
    lines.push('');
  });
  if (!dsl.steps.find(s => s.$op === 'output')) lines.push(`    return data`);
  return lines.join('\n');
}

function genSQL(dsl) {
  const sourceNames = Object.keys(dsl.sources);
  let ctes = [];
  let mainQuery = '';

  sourceNames.forEach(name => {
    const src = dsl.sources[name];
    const cols = Array.isArray(src.select) ? src.select.join(', ') : '*';
    ctes.push(`${name}_src AS (\n  SELECT ${cols}\n  FROM ${name}\n)`);
  });

  dsl.steps.forEach((step, i) => {
    const from = Array.isArray(step.$from) ? step.$from[0] : (step.$from || 'data');
    const nm = `step_${i+1}`;
    if (step.$op === 'filter') {
      ctes.push(`${nm} AS (\n  SELECT *\n  FROM ${from}\n  WHERE ${step.where || '1=1'}\n)`);
    } else if (step.$op === 'join') {
      const right = Array.isArray(step.$from) ? step.$from[1] : 'right_tbl';
      ctes.push(`${nm} AS (\n  SELECT l.*, r.*\n  FROM ${from} l\n  ${(step.type||'INNER').toUpperCase()} JOIN ${right} r ON l.${step.on} = r.${step.on}\n)`);
    } else if (step.$op === 'aggregate') {
      ctes.push(`${nm} AS (\n  SELECT ${step.fn.toUpperCase()}(${step.field}) AS ${step.fn}_${step.field}\n  FROM ${from}\n)`);
    } else if (step.$op === 'groupby') {
      const by = (step.by || []).join(', ');
      ctes.push(`${nm} AS (\n  SELECT ${by}, COUNT(*) AS count\n  FROM ${from}\n  GROUP BY ${by}\n)`);
    } else if (step.$op === 'sort') {
      ctes.push(`${nm} AS (\n  SELECT *\n  FROM ${from}\n  ORDER BY ${step.by} ${(step.order||'asc').toUpperCase()}\n)`);
    } else if (step.$op === 'map') {
      const cols = (step.fields||[]).map(f => f).join(', ') || '*';
      ctes.push(`${nm} AS (\n  SELECT ${cols}\n  FROM ${from}\n)`);
    } else if (step.$op === 'output') {
      mainQuery = `\n-- Final: ${step.name}\nSELECT * FROM ${from};`;
    }
  });

  return `-- Generated by ViewForge\n-- Pipeline: ${dsl.$pipeline}\n\nWITH\n${ctes.join(',\n\n')}${mainQuery || '\nSELECT * FROM data;'}`;
}

function copyCode() {
  navigator.clipboard.writeText(document.getElementById('codegen-output').textContent).catch(()=>{});
  document.getElementById('status-msg').textContent = 'Code copied!';
  setTimeout(()=> document.getElementById('status-msg').textContent = '', 2000);
}